#!/bin/sh

#Dependencies
#	wireless device
#	ethernet device
#	wireless_tools package
#	nerdfont
#	network-rx script
#Info
#	prints out what connection is used, name and signal strength if applicable,
#	and how many bytes are being received

wireless_device="wlan0"
ethernet_device="enp0s25"

wifi_status=$(cat /sys/class/net/"$wireless_device"/operstate 2>/dev/null)
ether_status=$(cat /sys/class/net/"$ethernet_device"/operstate 2>/dev/null)
output=""

# Ethernet has higher priority under my systemd-networkd RouteMetric
if [[ "$ether_status" == "up" ]]; then
	output+="󰈀 eth | $(network-rx "$ethernet_device")"
elif [[ "$wifi_status" == "up" ]]; then
	ssid=$(iwgetid -r)
	if [[ -n "$ssid" ]]; then
		#wifi icon
		output+="󰖩 $ssid "

		signal=$(awk 'NR==3 {print substr($3,0,2)}' /proc/net/wireless)
		output+="$signal% | "
		output+=$(network-rx "$wireless_device")
	else
		output+="󱚵 NO SIGNAL"
	fi
else
	output+="󱐅"
fi

echo "$output"
